version: '3.2'

services:
  backend:
    build:
      context: ./
    env_file:
      - env/prod.app.env
    ports:
      - '3005:3005'
    networks:
      - iposter_network_local

#  postgresql_local:
#    build: docker/postgres/.
#    env_file:
#      - env/local.pg.env
#    ports:
#      - '5454:5432'
#    networks:
#      - iposter_network_local
#    volumes:
#      - ./pg_data_local:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - iposter_network_local

#  minio_local:
#    image: minio/minio
#    entrypoint: sh
#    command: -c 'mkdir -p /export/images && minio server /export'
#    env_file:
#      - env/local.minio.env
#    ports:
#      - '9000:9000'
#    networks:
#      - iposter_network_local
#    volumes:
#      - ./minio_data_local:/var/lib/minio/data

volumes:
  pg_data_local:
  minio_data_local:

networks:
  iposter_network_local:
    driver: bridge
